fix: context binding in addModel
rematch/rematch pull request #873
Opened 2021-03-01 10:13 UTC by objectisundefined

for issue https://github.com/rematch/rematch/issues/872

2021-03-01 11:17 UTC, semoal requested changes

2021-03-01 11:17 UTC, semoal commented on packages/core/test/init.test.ts
> +	test('addModel works when it was used alone', () => {
move this test better to `store.test.ts` please, we already have there some tests related to storeModel =)

2021-03-01 11:56 UTC, semoal approved these changes

2021-03-02 01:37 UTC, tianzhich commented
Looks great! The `bind` does nothing here, change `this` to `rematchStore` would be better. Thanks for contributing @objectisundefined

2021-03-02 01:39 UTC, tianzhich commented
I merged, you can publish in your free time @semoal

2021-03-02 01:39 UTC, merged